server:
  port: 8083
spring:
  application:
    name: indexing-service

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: alpha
    tagsSorter: alpha
elasticsearch:
  uri: http://localhost:9200
  index-name: pdf_content
